coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "_build/**"
  - "c_build/**"
  - "priv/**"
  - "msquic/**"
