on: ["push", "pull_request"]

name: Test Coverage

permissions:
  contents: read
  id-token: write

jobs:
  run-cover:
    name: Run Cover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - '27'
        rebar3:
          - '3.23.0'
        build_type:
          - RelWithDebInfo
        logging:
          - false
        arch:
          - x86_64
        openssl:
          - quictls
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
      with:
        otp-version: ${{ matrix.otp }}
        rebar3-version: ${{ matrix.rebar3 }}

    - name: Start epmd
      run: |
        epmd -daemon
        epmd -names

    - name: Run cover
      env:
        QUICER_TLS_VER: ${{ matrix.openssl }}
      run: |
        sudo apt-get install lcov
        export QUICER_TLS_VER
        make cover

    - name: Codecov C
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        use_oidc: true
        files: coverage/proper-lcov.info,coverage/lcov.info
        flags: c-lcov-${{ matrix.openssl }}
        disable_search: true
        fail_ci_if_error: false

    - name: Generate Codecov Erlang report
      run: |
        rm -f codecov.json
        rebar3 codecov analyze path="_build/test/cover"

    - name: Codecov Erlang
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        use_oidc: true
        files: codecov.json
        flags: erlang-${{ matrix.openssl }}
        disable_search: true
        fail_ci_if_error: false
