name: lux
on: [push, pull_request]

jobs:
  run-lux-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - '26.2.5'
          - '27.3'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.23.0'

      - name: build lux
        run: |
          git clone https://github.com/hawk/lux.git
          cd lux
          autoconf
          ./configure
          make
          sudo make install

      - name: run example tests
        run: |
          which lux
          make
          cd test/example
          make all lux
